export { createAdminController } from './adminDI';
export { createAuthController } from "./authDI";
export { createChatController } from "./chatDI";
export { createDoctorController } from "./doctorDI";
export { createPrescriptionController } from "./prescriptionDI";
export { createReviewController } from "./reviewDI";
export { createSlotController } from "./slotDI";
export { createUserController } from "./userDI";
export { createAppointmentController } from "./appointmentDI";
